owner: Sec31
repo: status
user-agent: S31-Data

sites:
  - name: "TNR: Pterodactyl Panel"
    url: https://panel.truenorthroleplay.net
    icon: https://panel.truenorthroleplay.net/favicons/apple-touch-icon.png
    assignees:
      - ItsAGeekThing
  - name: "TNR: Pterodactyl Wings (Node #01)"
    url: $PTYL_WINGS1
    icon: https://panel.truenorthroleplay.net/favicons/apple-touch-icon.png
    expectedStatusCodes:
      - 401
    assignees:
      - ItsAGeekThing
  - name: "EXT: Rex's ARK"
    url: https://panel.truenorthroleplay.net/api/client/servers/$PTYL_REXARK_UUID/resources
    headers:
      - "Authorization: Bearer $PTYL_CLIENT_KEY"
      - "Content-Type: application/json"
      - "Accept: application/json"
    __dangerous__body_down: "stopped"
    __dangerous__body_degraded: "starting"
    assignees:
      - T-MrRex

status-website:
  cname: status.section31.earth
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "S31: System Status"
  introTitle: "Section 31 System Status"
  introMessage: "Welcome to Section 31's home for real-time and historical data on system performance."
  navbar:
    - title: Status
      href: /
      
commitMessages:
  commitAuthorName: "CMDR Data"
  commitAuthorEmail: "cmdr_data@section31.earth"
  
i18n:
  footer: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
